import { Component } from '@angular/core';

@Component({
  selector: 'calendar-component-calendar-all-week',
  templateUrl: './component-calendar-all-week.component.html',
  styleUrls: ['./component-calendar-all-week.component.css'],
})
export class ComponentCalendarAllWeekComponent {
  date = new Date();
  day = this.date.getDay();
  dayOfMonth = this.date.getDate();
  month = this.date.getMonth() + 1;
  year = this.date.getFullYear();
  daysName = [];
  monthsName = [];
  timesOfDay = [];

  allDays = [];

  ngOnInit() {
    this.daysName = [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ];
    this.monthsName = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    this.timesOfDay = [
      '00.00',
      '01.00',
      '02.00',
      '03.00',
      '04.00',
      '05.00',
      '06.00',
      '07.00',
      '08.00',
      '09.00',
      '10.00',
      '11.00',
      '12.00',
      '13.00',
      '14.00',
      '15.00',
      '16.00',
      '17.00',
      '18.00',
      '19.00',
      '20.00',
      '21.00',
      '22.00',
      '23.00',
    ];
    this.allDays = [
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'DOLU',
        saturday: 'BOS',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'BOS',
        wednesday: 'BOS',
        thursday: 'BOS',
        friday: 'BOS',
        saturday: 'BOS',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'DOLU',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'BOS',
        saturday: 'DOLU',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'DOLU',
        friday: 'BOS',
        saturday: 'DOLU',
        sunday: 'BOS',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'BOS',
        saturday: 'BOS',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'DOLU',
        saturday: 'DOLU',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'DOLU',
        saturday: 'BOS',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'DOLU',
        saturday: 'BOS',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'BOS',
        saturday: 'DOLU',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'BOS',
        saturday: 'BOS',
        sunday: 'DOLU',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'DOLU',
        saturday: 'DOLU',
        sunday: 'BOS',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'DOLU',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'BOS',
        saturday: 'BOS',
        sunday: 'DOLU',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'DOLU',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'DOLU',
        saturday: 'DOLU',
        sunday: 'BOS',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'DOLU',
        wednesday: 'BOS',
        thursday: 'BOS',
        friday: 'DOLU',
        saturday: 'BOS',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'DOLU',
        friday: 'BOS',
        saturday: 'DOLU',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'DOLU',
        friday: 'DOLU',
        saturday: 'DOLU',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'BOS',
        wednesday: 'DOLU',
        thursday: 'DOLU',
        friday: 'DOLU',
        saturday: 'DOLU',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'DOLU',
        wednesday: 'DOLU',
        thursday: 'DOLU',
        friday: 'DOLU',
        saturday: 'DOLU',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'DOLU',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'BOS',
        saturday: 'DOLU',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'DOLU',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'DOLU',
        saturday: 'DOLU',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'DOLU',
        wednesday: 'DOLU',
        thursday: 'BOS',
        friday: 'DOLU',
        saturday: 'BOS',
        sunday: 'BOS',
        status: 'bos',
      },
      {
        id: '1000',
        monday: 'BOS',
        tuesday: 'DOLU',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'BOS',
        saturday: 'DOLU',
        sunday: 'DOLU',
        status: 'dolu',
      },
      {
        id: '1000',
        monday: 'DOLU',
        tuesday: 'DOLU',
        wednesday: 'BOS',
        thursday: 'DOLU',
        friday: 'BOS',
        saturday: 'BOS',
        sunday: 'DOLU',
        status: 'bos',
      },
    ];
  }

  getSeverity(status: string) {
    switch (status) {
      case 'DOLU':
        return 'dolu';
      case 'BOS':
        return 'bos';
    }
    return null;
  }
}
