import { ServiceBox } from './app/models/ServiceBox';

export const sample_services: ServiceBox[] = [
  {
    id: 1,
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
    stars: '4',
    title: 'We transplant your hair in a professional way',
    price: '16000',
  },
  {
    id: 2,
    stars: '5',
    title: 'We quickly overcome the problems of your eyes',
    price: '12000',
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
  },
  {
    id: 3,
    stars: '5',
    title: 'We do your rhinoplasty without any problems',
    price: '24000',
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
  },
  {
    id: 4,
    stars: '4',
    title: 'The most admired business of aesthetics in Turkey',
    price: '29000',
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
  },
  {
    id: 5,
    stars: '5',
    title: 'The most admired business of aesthetics in Turkey',
    price: '50000',
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
  },
  {
    id: 6,
    stars: '5',
    title: 'Best professor in USA',
    price: '125000',
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
  },
  {
    id: 7,
    stars: '5',
    title: 'Everyone try to reach me out for treatment',
    price: '24100',
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
  },
  {
    id: 8,
    stars: '4',
    title: 'You do not feel anything, it will be super easy',
    price: '15000',
    images: [
      'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9jdG9yfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',
    ],
    country: 'United States',
    city: 'San Francisco',
    aboutService: 'Our service is available in order to provide best for you',
    threeSteps: [
      'First step will be here',
      'Second step will be here',
      'Third step will be here',
    ],
    youNeedToKnow: [
      'First needed will be here',
      'Second needed will be here',
      'Third needed will be here',
      'Fourth needed will be here',
    ],
  },
];
